# Collaborators: 
none

# Question 1

(a) Find out how to sample t elements from a pandas dataframe of k ≥ t elements without
replacement (i.e., a name cannot appear twice on the resulting list). Give an example.
Hint: You can use random.sample or numpy.random.choice. You can also write a
function for this yourself from scratch.


In [36]:
from random import sample
list1 = [1,2,3,4]
sample(list1, 2)

[3, 2]

(b) Create an arbitrary list of 18 different names of cars. (It can be as simple as “A”, “B”, . .
. , “R”, but you are invited to be more creative. It could, for instance, start from “Fiat
500” and “Ferrari Testarossa”.) Then create two data frames, with 10 rows each, as
follows.
>• The first one—say, df1—should have two labeled columns: Name and MPG (i.e.,
miles per gallon). The names should be selected at random from the list of names
without replacement. The values in the other column should be independent
random real numbers from 5 to 50.

>• The second one—say, df2—should have two labeled columns: Name and
SecondsTo60 (i.e., time needed to reach 60 mph). Names should be selected in
the same way as in df1, but independently of the selection in df1. The values in
the other column should be independent random real numbers from 1 to 20.


In [43]:
import pandas as pd
import numpy as np
list2 = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R"]
MPG = np.random.randint(5,50,size=(10))
df1 = pd.DataFrame({'Name': sample(list2,10), 'MPG': MPG})
print(df1)


seconds = np.random.randint(1,20,size=(10))
df2 = pd.DataFrame({'Name': sample(list2,10), 'SecondsTo60': seconds})
print(df2)


  Name  MPG
0    C   36
1    J   27
2    A   26
3    N   45
4    L   17
5    M   40
6    B   22
7    R   26
8    I    7
9    D    8
  Name  SecondsTo60
0    L            5
1    I           12
2    M            4
3    H            8
4    O            4
5    J            3
6    D           10
7    C            1
8    B            7
9    R           19


(c) Combine df1 and df2 to create a new data frame, df, with three columns: Name, MPG,
and SecondsTo60. The resulting data frame should have at most one row for each car.
A car should appear in df if and only if it appears in at least one of df1 and df2. If the
value of MPG or SecondsTo60 for a given car appears in df1 or df2, respectively, then
it should be included in the new data frame. Otherwise, use NaN.


In [44]:
df = pd.merge(df1, df2, how = "outer",on=["Name"])
df

Name   MPG  SecondsTo60
0     C  36.0          1.0
1     J  27.0          3.0
2     A  26.0          NaN
3     N  45.0          NaN
4     L  17.0          5.0
5     M  40.0          4.0
6     B  22.0          7.0
7     R  26.0         19.0
8     I   7.0         12.0
9     D   8.0         10.0
10    H   NaN          8.0
11    O   NaN          4.0

(d) Fix all occurrences of NaN in df. First, replace all NaN‘s in the MPG column with the
mean of values in this column for all cars. Second, replace all NaN‘s in the
SecondsTo60 column by the maximum of values in this column for all cars.


In [45]:
values = {"MPG": df.mean()[0], "SecondsTo60": df.max()[2]}
df = df.fillna(value=values)
df

C:\Users\Emily\AppData\Local\Temp\ipykernel_26392\1185496620.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  values = {"MPG": df.mean()[0], "SecondsTo60": df.max()[2]}


Name   MPG  SecondsTo60
0     C  36.0          1.0
1     J  27.0          3.0
2     A  26.0         19.0
3     N  45.0         19.0
4     L  17.0          5.0
5     M  40.0          4.0
6     B  22.0          7.0
7     R  26.0         19.0
8     I   7.0         12.0
9     D   8.0         10.0
10    H  25.4          8.0
11    O  25.4          4.0

(e) Add “Awesome ” as a prefix to the name of each car in df.


In [46]:
df["Name"] = df['Name'].apply(lambda name: "Awesome" + name)
df

Name   MPG  SecondsTo60
0   AwesomeC  36.0          1.0
1   AwesomeJ  27.0          3.0
2   AwesomeA  26.0         19.0
3   AwesomeN  45.0         19.0
4   AwesomeL  17.0          5.0
5   AwesomeM  40.0          4.0
6   AwesomeB  22.0          7.0
7   AwesomeR  26.0         19.0
8   AwesomeI   7.0         12.0
9   AwesomeD   8.0         10.0
10  AwesomeH  25.4          8.0
11  AwesomeO  25.4          4.0

(f) Create a new data frame, df_eco, from df by selecting rows for which MPG is strictly
greater than the median of values for all cars.

In [47]:
df_eco = df[df['MPG'] > df.median()[0]]
df_eco

C:\Users\Emily\AppData\Local\Temp\ipykernel_26392\1547504243.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_eco = df[df['MPG'] > df.median()[0]]


Name   MPG  SecondsTo60
0  AwesomeC  36.0          1.0
1  AwesomeJ  27.0          3.0
2  AwesomeA  26.0         19.0
3  AwesomeN  45.0         19.0
5  AwesomeM  40.0          4.0
7  AwesomeR  26.0         19.0

# Question 2

## Creating the files

In [14]:
import csv
# data rows as dictionary objects 
ingredients ={'Yeast': 57.5, 'Flour': 112.5, 'Sugar': 245}

# field names 
fields = ['Yeast', 'Flour', 'Sugar'] 

with open('ingredients.csv', 'w', newline='') as file: 
    writer = csv.DictWriter(file, fieldnames = fields)
    writer.writeheader() 
    writer.writerow(ingredients)

file.close()

In [16]:
import numpy as np 
ingredients = np.round(np.random.uniform(0.5, 3, (10,3)),2)
price = np.round(np.random.uniform(2, 7, (10,1)),2)
name = np.empty((10,1))
values = np.concatenate((name, price, ingredients), axis=1)
print(values)
np.savetxt('pastries.csv',  values, delimiter=',',header = 'Name,Price,Yeast,Flour,Sugar')

[[4.16 2.54 1.47 2.79 1.64]
 [6.89 3.48 2.17 2.04 0.75]
 [5.43 4.33 1.46 1.68 2.26]
 [2.46 4.23 1.64 0.87 2.91]
 [3.33 6.36 2.57 2.03 1.38]
 [2.24 2.73 2.88 2.04 1.9 ]
 [3.9  4.08 2.   2.34 0.73]
 [2.75 3.77 1.43 1.5  0.66]
 [2.4  3.28 1.06 1.02 1.95]
 [4.51 2.41 2.47 1.57 1.35]]


Add the name of pastries by hand 

## Start Approaching to the Problem

In [114]:
import pandas as pd
filename1 = 'ingredients.csv'
data1 = pd.read_csv(filename1, sep=',')
print(data1)

   Yeast  Flour  Sugar
0   57.5  112.5    245


In [115]:
filename2 = 'pastries.csv'
data2 = pd.read_csv(filename2, sep=',')
print(data2)

             Name  Price  Yeast  Flour  Sugar
0          Cookie   2.54   1.47   2.79   1.64
1  GingerBreadMan   3.48   2.17   2.04   0.75
2            Cake   4.33   1.46   1.68   2.26
3      CheeseCake   4.23   1.64   0.87   2.91
4           Bread   6.36   2.57   2.03   1.38
5        ApplePie   2.73   2.88   2.04   1.90
6       Croissant   4.08   2.00   2.34   0.73
7           Donut   3.77   1.43   1.50   0.66
8           Bagel   3.28   1.06   1.02   1.95
9         Cupcake   2.41   2.47   1.57   1.35


### Our Goal For This Question

* variables: x1,x2,x3,x4,...,x10
> where x's are the numbers of each pastry

* linear constraints:
  $$x \ge 0$$
  $$\sum_{i=1}^{10} y_ix_i\le57.5$$
  $$\sum_{i=1}^{10} f_ix_i\le112.5$$
  $$\sum_{i=1}^{10} s_ix_i\le245$$

* **Goal:** maximize $\sum_{i=1}^{10} p_ix_i$
> Since I will use scipy to do optimization and it only minimizes functions, I convert my goal into: minimize $\sum_{i=1}^{10} -p_ix_i$ 


In [150]:
from scipy.optimize import linprog
import numpy as np 
# Set up the coefficients for the function we want to minimize
c = np.asarray(-data2['Price'])

In [151]:
# Set up the A_ub, which contains the coefficients of the left hand side of inequations 
y = []
f = []
s = []
for val in data2['Yeast']:
    y.append(val)   
for val in data2['Flour']:
    f.append(val)
for val in data2['Sugar']:
    s.append(val)
A_ub = [y,f,s]
A_ub

[[1.47, 2.17, 1.46, 1.64, 2.57, 2.88, 2.0, 1.43, 1.06, 2.47],
 [2.79, 2.04, 1.68, 0.87, 2.03, 2.04, 2.34, 1.5, 1.02, 1.57],
 [1.64, 0.75, 2.26, 2.91, 1.38, 1.9, 0.73, 0.66, 1.95, 1.35]]

In [152]:
# Set up the b_ub, which contains the right hand side of inequations 
b_ub = [data1.iloc[0][0], data1.iloc[0][1], data1.iloc[0][2]]
b_ub

[57.5, 112.5, 245.0]

In [173]:
# Set up the boundaries 
bounds = [(0,None) for i in range(10)]
bounds

[(0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None),
 (0, None)]

In [178]:
# Optimization 
opt = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method="highs")
print("status =",opt.status, "iters=", opt.nit, "negative profit=", opt.fun, "\nx=\n", opt.x)
max_profit = -opt.fun


status = 0 iters= 1 negative profit= -177.92452830188677 
x=
 [ 0.          0.          0.          0.          0.          0.
  0.          0.         54.24528302  0.        ]


In [180]:
# Demonstrade the results 
print("The max profit is", max_profit, "and can be achieved by producing")
for i in range(10): 
    print(data2['Name'][i], ":", opt.x[i] , "pieces")

The max profit is 177.92452830188677 and can be achieved by producing
Cookie : 0.0 pieces
GingerBreadMan : 0.0 pieces
Cake : 0.0 pieces
CheeseCake : 0.0 pieces
Bread : 0.0 pieces
ApplePie : 0.0 pieces
Croissant : 0.0 pieces
Donut : 0.0 pieces
Bagel : 54.24528301886792 pieces
Cupcake : 0.0 pieces


## Summary 


When solving the problem, I fiirst expressed the dependent variable (i.e. the total profit we make) as a function of the independent variables (i.e. the number of each pastry); and our goal for this problem is to find out the values of independent variables that maximize the value of this dependent vairable. Then, I listed out all the constraints. When everything needed to consider/achieve is clear, I chose the `scipy.optimize.linprog` to solve this problem; and since this algorithm only minimizes functions, I convert my goal of this optimization process from maximizing the function into minimizing the negative of the function. When applying the algorithm, I pluged in the coefitients of our function and the informations of the constraints. Lastly, I negatived the value of the optimized function to get the maximum total profit. 

# Question 3 

I've spent about 8 hours on this HW. 

# Resources: 
Lecture Note_08